### ISSUE TITLE
Update this for future pypixelbuf 2.0.0

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#14]
It updates the PixelBuf API to match late changes in CircuitPython. https://github.com/adafruit/Adafruit_CircuitPython_Pypixelbuf/compare/1.0.3...master

@dunkmann00 We'll need this before we can release pypixelbuf. Ideally the new versions of both would be released in the same bundle.

**Comment by ladyada** [comment]
@caternuson wanna take a stab at it?

**Comment by tannewt** [comment]
Fixed by #15 Thanks @dunkmann00!
