### ISSUE TITLE
SPI Buffer Size

### ISSUE THREAD

**Issue by antoinericha** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#18]
Hello,

I am trying to control 300 LED from an nvidia xavier nx. I used the neopixel_spi since neopixel is not supported by nvidia.

I am now able to control 168 LED since the buffer size is 4096 only. I increased the bufsiz to 65535 but still I have the same issue.

Is there a solution from the neopixel_spi library to solve this problem, or it is a pure hardware issue.

Thank you.

**Comment by caternuson** [comment]
@makermelissa Do you know if this is something specific to the Jetson Xavier? I don't have any experience with that hardware platform.

**Comment by antoinericha** [comment]
From the Xavier part, I was able to increase the bufsize to 65535. but is still not showing any difference with LED number. I asked nvidia for help to check if it is a problem related to the hardware.

But here I am checking if I can control the buffer size from the script. Till now I only can send the RGB color which is 24 bit for each LED

**Comment by makermelissa** [comment]
@caternuson I have not worked with the Xavier NX before. I have only used the Jetson Nano and when I used it, it didn't even have SPI available without some major work.

**Comment by antoinericha** [comment]
The Xavier NX is almost the same as nano with the SPI configuartion. it needs a basic configuration to turn it on in the board using 2 or 3 command lines.
But concerning the buffer size, I solved it and I am capable of running more than 168 LED = 4096 bufsiz.
It can be solved by changing the bufsize in the board and inside the neopixel SPI library.

**Comment by evaherrada** [comment]
Closing. I'm pretty sure this is resolved. @antoinericha let me know if it isn't and I can reopen the issue.

**Comment by osinpl** [comment]
> neopixel SPI library

Hi I have the same problem on jetson nano need to control 288 leds and it seems to be not possible, I checked with andruino and there is no problem. Can you let me know where exactly you made changes in your case?
