### ISSUE TITLE
The RESET signal is too long

### ISSUE THREAD

**Issue by apalou21** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#2]
Hello dear maintainers,

I was curious and had a look at the Neopixel library code; I found that the initialization of the RESET on line 277 in the neopixel.py file set a 512 (6400000 * 80e-6) bytes long pattern, which is 8 times too much to get a 80us '0' line. This will slow down the refresh cycle for each Neopixel strip.

**Comment by caternuson** [comment]
Good catch. Each byte is 8 clock cycles, so agree, this is missing a divide by 8.

Are you interested in trying to make a pull request for this? This would be a good first one if you've never done one.

**Comment by apalou21** [comment]
Hello caternuson,

I'm sorry for the late answer, but I'm so busy this end of year I can't have regular look here.
Sure it will be interesting to participate, unfortunately I'm not used to the process and I never used Git. As I mention before I'm really busy now and don't have much time until Christmas (so much to do before that).

**Comment by caternuson** [comment]
@apalou21 OK, I went ahead and took care of this as part of another PR. Thanks again for pointing that out. If you want to try a PR in the future, there are these guides which might help:
https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control
https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github
But at some point, just jump in and give it a try.
