### ISSUE TITLE
One LED not turning ON

### ISSUE THREAD

**Issue by nanogear** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#23]
Hello, 

I am using this example code on a NVIDIA Jetson Nano and a NeoPixel Stick - 8 x WS2812 5050 RGB LED. 

Everything installed correctly. One of the LED´s is not turning ON when running the code. Any advice? (The Led´s turns on in sequence. One at a time but the 5th led is always off).

Thank you and kind rgards

**Comment by caternuson** [comment]
This is probably better handled in the forums:
https://forums.adafruit.com/
since it may be more of a hardware issue. Please post there with photos of your setup.

**Comment by nanogear** [comment]
Thank you!!
