### ISSUE TITLE
NeoPixel LED strip stopped working on nvidia NX board

### ISSUE THREAD

**Issue by AmeyHande** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#24]
Hello,
I had NeoPixel LED working on NX board by following instructions given adafruit website.
It stopped working all of sudden, when I reconnected LED strip at same GPIO pins (Pin 2- 5 volts, Pin 6 - GND and Pin 19 - Data I/P). They are not working anymore, I have even tried new LED strip (thinking previous one went bad) but even that didn't worked.
I'm running basic neopixel_test code.
Can anyone help me?

Best,
Amey Hande

**Comment by caternuson** [comment]
It was working then not working. So something happened, most likely with the hardware. Please post in the forums for hardware support:
https://forums.adafruit.com/
