### ISSUE TITLE
Neopixel timing issue with SPI1 on Raspberry Pi?

### ISSUE THREAD

**Issue by Redrocirt** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#26]
After I figured out how to [controll Neopixels via SPI0 (GPIO 10)](https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel_SPI/issues/25) I tried to change my setup to use [SPI1 (GPIO 20)](https://de.pinout.xyz/pinout/pin38_gpio20#).

Unfortunatelly I'm getting the same strange results (wrong colors) like in my previous tests (before I changed bit0).

I added `dtoverlay=spi1-3cs` in _/boot/config.txt_ to activate the second SPI and rebooted.

My updated test script:

```
import time
import board
import neopixel_spi as neopixel

NUM_PIXELS = 4
PIXEL_ORDER = neopixel.GRB
DELAY = 1

# spi = board.SPI()
# use SPI1:
from busio import SPI
spi = SPI(clock=board.SCK_1)

pixels = neopixel.NeoPixel_SPI(
    spi, NUM_PIXELS, brightness=0.1, auto_write=False, pixel_order=PIXEL_ORDER, bit0=0b10000000
)

print("All neopixels OFF")
pixels.fill((0,0,0))
pixels.show()
time.sleep(DELAY)

print("One neopixel red")
pixels[0] = (255,0,0)
pixels.show()
time.sleep(DELAY)

print("All neopixels green")
pixels.fill((0,255,0))
pixels.show()
time.sleep(DELAY)

print("All neopixels OFF")
pixels.fill((0,0,0))
pixels.show()
time.sleep(DELAY)

print("End of test")
```

I haven't found a solution to this yet, but maybe this is related:

There are some forum threads about "timing irregularities" with SPI1 on Raspberry Pi:
[https://www.raspberrypi.org/forums/viewtopic.php?t=237337](https://www.raspberrypi.org/forums/viewtopic.php?t=237337)
[https://www.raspberrypi.org/forums/viewtopic.php?t=181154](https://www.raspberrypi.org/forums/viewtopic.php?t=181154)

There seems to be a timing gap on SPI1 that breaks the bit order required by the Neopixels (if I got that right)

They talk about setting `DLEN=2`. Can this be done from within the Python script when the SPI is initialized?

**Comment by ladyada** [comment]
honestly.... this is a hack on top of a hack. you should look for another way to drive the pixels you want
