### ISSUE TITLE
Neopixels overwrite when executed from .Net application  

### ISSUE THREAD

**Issue by illusean** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#29]
Hello all,

I followed the guide to drive Neopixels from a Jetson Nano via SPI [here](https://learn.adafruit.com/circuitpython-libraries-on-linux-and-the-nvidia-jetson-nano/neopixels-with-spi)

Everything works as expected and I am able to drive two daisy-chained 144 LED/ meter strips successfully via the terminal window with a command like : `python3 LEDController.py -d 10 -t 11 - b 5`

However when I try to execute the same script from a .Net (.Net core 3.1)application via the System.Process class I'm getting strange overwriting behavior. Here is the snippet where I execute the script:

```
string file = "Python/LEDController.py";
string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, file);
Process proc = new System.Diagnostics.Process();
proc.StartInfo.FileName = "python3";
proc.StartInfo.Arguments = path + $" -d {nominal} -t {max} -b 5 ";
proc.StartInfo.UseShellExecute = false;
proc.StartInfo.RedirectStandardOutput = true;
proc.StartInfo.RedirectStandardError = true;                
processStarted = proc.Start();
```

Another bit of information that I find strange is that the .Net application is able to drive 1 144 LED/meter strip fine but when I modify the python script to include the second strip (i.e. changing NUM_PIXELS to 288 for 2 strips) it will ignore the second strip and begin overwriting the first giving a weird blinking animation with no persistence in the LEDS, they blink on then immediately off. Since I'm able to get 2 strips to work w/o issues in the terminal would this point to an env variable issue?

I understand that this might be out of scope for this forum but I was hoping someone might be able to provide me with some insight as to why this behaviors is occurring. 

Kind Regards

**Comment by illusean** [comment]
For those who have this problem. Raising the default buffer size on this [line ](https://github.com/adafruit/Adafruit_Python_PureIO/blob/f4d0973da05b8b21905ff6bab69cdb652128f342/Adafruit_PureIO/spi.py#L72) fixed the problem

**Comment by siddharthcb** [comment]
hello   @illusean ,
i am trying to get the neopixe work with jetson nano as well but strangely I cannot get it working. I am referring to the same link as you posted. Is there any addional steps you followed to get it working?

**Comment by caternuson** [comment]
Closing. Seems like original issue was fixed. @siddharthcb unless you are also using .Net, please post in the forums first with details of your hardware setup:
https://forums.adafruit.com/
