### ISSUE TITLE
Light turns on for about 0.1 seconds and then turns off

### ISSUE THREAD

**Issue by 42willow** [adafruit/Adafruit_CircuitPython_NeoPixel_SPI#32]
Code:
```py
import time
import board
import neopixel_spi as neopixel

NUM_PIXELS = 600
PIXEL_ORDER = neopixel.RGB
COLORS = (0xFF0000, 0x00FF00, 0x0000FF)

spi = board.SPI()

pixels = neopixel.NeoPixel_SPI(spi,
                               NUM_PIXELS,
                               pixel_order=PIXEL_ORDER,
                               auto_write=False)
pixels[100] = COLORS[1]
pixels.show()
time.sleep(1)
```

**Comment by caternuson** [comment]
What main board are you running this on?

What NeoPixels are being used?

How are the NeoPixels connected?

How are you powering the 600 NeoPixels?

What if you only try to light the first NeoPixel? `pixels[0] = COLORS[1]

**Comment by 42willow** [comment]
Unfortunately I cannot test this now as I have just reset my Raspberry Pi's operating system. 😅

**Comment by caternuson** [comment]
OK, board is a Raspberry Pi. Got that much at least.

Will you be able to test eventually? If not, please close issue. Alternatively, please post in the forums, as this seems most likely a hardware issue:
https://forums.adafruit.com/
